# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ie-bank-frontend

on:
  push:
    branches:
      - '*'
    # Exclude the main branch for Development environment
      - '!main'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: chiaradigi-fe-dev
  FRONTEND_WEBAPP_UAT: chiaradigi-fe-uat
  CHANNEL_ID: 'C066QRSD15E'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: build for dev
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev ## this command will build the vue.js app using .env.development variables into the dist-dev/ folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-dev
          path: dist-dev/

      - name: build for uat
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat ## this command will build the vue.js app using .env.uat variables into the dist-uat/ folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-dev

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

      - name: Post deployment status to Slack
        id: slack-notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: env.CHANNEL_ID
          slack-message: "Deployment to DEV completed: ${{ job.status }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'User Acceptance Testing'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-uat

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .
      
      - name: Post deployment status to Slack
        id: slack-notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: env.CHANNEL_ID
          slack-message: "Deployment to UAT completed: ${{ job.status }}"
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}